# Statische CRT: DLL laeuft ohne installierte VC-Redistributable
# (behebt LoadLibrary-Fehler 126 "Modul nicht gefunden" auf Systemen
#  ohne vcruntime140.dll)
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
